language: java
sudo: false
install: true

jdk:
- oraclejdk8


script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar

after_success:
  - bash <(curl -s https://copilot.blackducksoftware.com/ci/travis/scripts/upload)
